exclude = ["venv*"]
line-length = 120
lint.ignore = [
    "PLR2004",
    "D104",
    "D107",
    "PT023",
    "PT001",
    "SIM300",  # "yoda conditions"
]
lint.select = [
    "B",    # bandit
    "C",   # complexity
    "D",   # docstrings
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "PT",  # flake8-pytest
    "RUF", # ruff base config
    "SIM", # flake-simplify
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
    "YTT", # flake8-2020
    # "ARG", # flake8-unused args
]
[lint.pydocstyle]
convention = "pep257"
